from typing import List

from pydantic import BaseModel, Field

from agents.base import call_llm
from agents.planner import Plan


class ReviewResult(BaseModel):
    approved: bool = Field(
        description="True if code is ready for testing, False if issues were found."
    )
    issues: List[str] = Field(
        description="Specific issues the Coder must fix. Empty list if approved."
    )


REVIEWER_SYSTEM_PROMPT = """
You are the Reviewer agent in a multi-agent coding team.
Your job is to read Python code generated by the Coder and check it against the spec and plan.

Evaluate:
1. Does it match the specification?
2. Are there obvious syntax errors or logical bugs?
3. Are the planned edge cases handled?

If the code looks solid, approve it. If not, reject it with specific, actionable issues.
Be brief and constructive.
"""


def review_code(code: str, spec: str, plan: Plan) -> ReviewResult:
    """
    Review generated code against the original spec and plan.

    Args:
        code: The Python code to review.
        spec: The original user specification.
        plan: The Plan produced by the Planner agent.

    Returns:
        ReviewResult with an approved flag and optional list of issues.
    """
    user_prompt = (
        f"Original Specification:\n<spec>\n{spec}\n</spec>\n\n"
        f"Planned Edge Cases:\n{chr(10).join(plan.edge_cases)}\n\n"
        f"Code to Review:\n<code>\n{code}\n</code>\n\n"
        f"Evaluate the code and return your ReviewResult."
    )

    review: ReviewResult = call_llm(
        system_prompt=REVIEWER_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        response_schema=ReviewResult,
    )
    return review
